# Generated by Django 3.0.3 on 2020-02-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pace',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
