# Generated by Django 3.0.3 on 2020-02-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0003_auto_20200220_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='race',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
