# Generated by Django 3.0.3 on 2020-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0005_auto_20200220_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
