# Generated by Django 3.0.3 on 2020-02-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0006_auto_20200220_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
