# Generated by Django 3.0.3 on 2020-02-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0007_auto_20200220_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
    ]
