# Generated by Django 3.0.3 on 2020-02-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0010_auto_20200223_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
