# Generated by Django 3.0.3 on 2020-02-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0011_workout_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='completed',
        ),
    ]
