# Generated by Django 3.0.3 on 2020-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0017_auto_20200225_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='race_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
