# Generated by Django 3.0.3 on 2020-02-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0018_schedule_race_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
