# Generated by Django 3.0.3 on 2020-02-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0019_schedule_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
