# Generated by Django 3.0.3 on 2020-02-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0020_schedule_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
