# Generated by Django 3.0.3 on 2020-03-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0022_auto_20200302_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
