# Generated by Django 3.0.3 on 2020-03-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0023_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
