# Generated by Django 3.0.3 on 2020-03-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0026_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
