import os 
from django.core.management.base import BaseCommand
from ...models import Activity

def half_marathon():
    Activity(race="half", week=1, day=1, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=1, day=2, workout_type="run", distance="2 miles").save()
    Activity(race="half", week=1, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=1, day=4, workout_type="rest").save()
    Activity(race="half", week=1, day=5, workout_type="run", distance="2 miles").save()
    Activity(race="half", week=1, day=6, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=1, day=7, workout_type="rest").save()

    Activity(race="half", week=2, day=1, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=2, day=2, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=2, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=2, day=4, workout_type="rest").save()
    Activity(race="half", week=2, day=5, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=2, day=6, workout_type="run", distance="5 miles").save()
    Activity(race="half", week=2, day=7, workout_type="rest").save()

    Activity(race="half", week=3, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=3, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=3, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=3, day=4, workout_type="rest").save()
    Activity(race="half", week=3, day=5, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=3, day=6, workout_type="run", distance="6 miles").save()
    Activity(race="half", week=3, day=7, workout_type="rest").save()

    Activity(race="half", week=4, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=4, day=2, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=4, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=4, day=4, workout_type="rest").save()
    Activity(race="half", week=4, day=5, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=4, day=6, workout_type="run", distance="7 miles").save()
    Activity(race="half", week=4, day=7, workout_type="rest").save()

    Activity(race="half", week=5, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=5, day=2, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=5, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=5, day=4, workout_type="rest").save()
    Activity(race="half", week=5, day=5, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=5, day=6, workout_type="run", distance="8 miles").save()
    Activity(race="half", week=5, day=7, workout_type="rest").save()

    Activity(race="half", week=6, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=6, day=2, workout_type="run", distance="5 miles").save()
    Activity(race="half", week=6, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=6, day=4, workout_type="rest").save()
    Activity(race="half", week=6, day=5, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=6, day=6, workout_type="run", distance="6 miles").save()
    Activity(race="half", week=6, day=7, workout_type="rest").save()

    Activity(race="half", week=7, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=7, day=2, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=7, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=7, day=4, workout_type="rest").save()
    Activity(race="half", week=7, day=5, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=7, day=6, workout_type="run", distance="9 miles").save()
    Activity(race="half", week=7, day=7, workout_type="rest").save()

    Activity(race="half", week=8, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=8, day=2, workout_type="run", distance="5 miles").save()
    Activity(race="half", week=8, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=8, day=4, workout_type="rest").save()
    Activity(race="half", week=8, day=5, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=8, day=6, workout_type="run", distance="6 miles").save()
    Activity(race="half", week=8, day=7, workout_type="rest").save()

    Activity(race="half", week=9, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=9, day=2, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=9, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=9, day=4, workout_type="rest").save()
    Activity(race="half", week=9, day=5, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=9, day=6, workout_type="run", distance="10 miles").save()
    Activity(race="half", week=9, day=7, workout_type="rest").save()

    Activity(race="half", week=10, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=10, day=2, workout_type="run", distance="6 miles").save()
    Activity(race="half", week=10, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=10, day=4, workout_type="rest").save()
    Activity(race="half", week=10, day=5, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=10, day=6, workout_type="run", distance="6 miles").save()
    Activity(race="half", week=10, day=7, workout_type="rest").save()

    Activity(race="half", week=11, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=11, day=2, workout_type="run", distance="5 miles").save()
    Activity(race="half", week=11, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=11, day=4, workout_type="rest").save()
    Activity(race="half", week=11, day=5, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=11, day=6, workout_type="run", distance="11 miles").save()
    Activity(race="half", week=11, day=7, workout_type="rest").save()

    Activity(race="half", week=12, day=1, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=12, day=2, workout_type="run", distance="5 miles").save()
    Activity(race="half", week=12, day=3, workout_type="crosstrain").save()
    Activity(race="half", week=12, day=4, workout_type="rest").save()
    Activity(race="half", week=12, day=5, workout_type="run", distance="4 miles").save()
    Activity(race="half", week=12, day=6, workout_type="run", distance="6 miles").save()
    Activity(race="half", week=12, day=7, workout_type="rest").save()

    Activity(race="half", week=13, day=1, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=13, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=13, day=3, workout_type="rest").save()
    Activity(race="half", week=13, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="half", week=13, day=5, workout_type="rest").save()
    Activity(race="half", week=13, day=6, workout_type="rest").save()
    Activity(race="half", week=13, day=7, workout_type="RACE DAY", distance="13.1 miles").save()

def five_k():
    Activity(race="5k", week=1, day=1, workout_type="crosstrain").save()
    Activity(race="5k", week=1, day=2, workout_type="rest").save()
    Activity(race="5k", week=1, day=3, workout_type="run", distance="1 mile").save()
    Activity(race="5k", week=1, day=4, workout_type="crosstrain").save()
    Activity(race="5k", week=1, day=5, workout_type="run", distance="1 mile").save()
    Activity(race="5k", week=1, day=6, workout_type="rest").save()
    Activity(race="5k", week=1, day=7, workout_type="run", distance="2 miles").save()

    Activity(race="5k", week=2, day=1, workout_type="crosstrain").save()
    Activity(race="5k", week=2, day=2, workout_type="rest").save()
    Activity(race="5k", week=2, day=3, workout_type="run", distance="2 miles").save()
    Activity(race="5k", week=2, day=4, workout_type="crosstrain").save()
    Activity(race="5k", week=2, day=5, workout_type="run", distance="1.5 miles").save()
    Activity(race="5k", week=2, day=6, workout_type="rest").save()
    Activity(race="5k", week=2, day=7, workout_type="run", distance="2 miles").save()

    Activity(race="5k", week=3, day=1, workout_type="crosstrain").save()
    Activity(race="5k", week=3, day=2, workout_type="rest").save()
    Activity(race="5k", week=3, day=3, workout_type="run", distance="2 miles").save()
    Activity(race="5k", week=3, day=4, workout_type="crosstrain").save()
    Activity(race="5k", week=3, day=5, workout_type="run", distance="1.5 miles").save()
    Activity(race="5k", week=3, day=6, workout_type="rest").save()
    Activity(race="5k", week=3, day=7, workout_type="run", distance="2.5 miles").save()
    
    Activity(race="5k", week=4, day=1, workout_type="crosstrain").save()
    Activity(race="5k", week=4, day=2, workout_type="rest").save()
    Activity(race="5k", week=4, day=3, workout_type="run", distance="2.5 miles").save()
    Activity(race="5k", week=4, day=4, workout_type="crosstrain").save()
    Activity(race="5k", week=4, day=5, workout_type="run", distance="2 miles").save()
    Activity(race="5k", week=4, day=6, workout_type="rest").save()
    Activity(race="5k", week=4, day=7, workout_type="run", distance="2.5 miles").save()

    Activity(race="5k", week=5, day=1, workout_type="crosstrain").save()
    Activity(race="5k", week=5, day=2, workout_type="rest").save()
    Activity(race="5k", week=5, day=3, workout_type="run", distance="2.5 miles").save()
    Activity(race="5k", week=5, day=4, workout_type="crosstrain").save()
    Activity(race="5k", week=5, day=5, workout_type="run", distance="2 miles").save()
    Activity(race="5k", week=5, day=6, workout_type="rest").save()
    Activity(race="5k", week=5, day=7, workout_type="run", distance="3 miles").save()

    Activity(race="5k", week=6, day=1, workout_type="crosstrain").save()
    Activity(race="5k", week=6, day=2, workout_type="rest").save()
    Activity(race="5k", week=6, day=3, workout_type="run", distance="2 miles").save()
    Activity(race="5k", week=6, day=4, workout_type="crosstrain").save()
    Activity(race="5k", week=6, day=5, workout_type="run", distance="1.5 miles").save()
    Activity(race="5k", week=6, day=6, workout_type="rest").save()
    Activity(race="5k", week=6, day=7, workout_type="RACE DAY", distance="3.1 miles").save()

def ten_k():
    Activity(race="10k", week=1, day=1, workout_type="rest").save()
    Activity(race="10k", week=1, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=1, day=3, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=1, day=4, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=1, day=5, workout_type="rest").save()
    Activity(race="10k", week=1, day=6, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=1, day=7, workout_type="run", distance="2 miles").save()

    Activity(race="10k", week=2, day=1, workout_type="rest").save()
    Activity(race="10k", week=2, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=2, day=3, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=2, day=4, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=2, day=5, workout_type="rest").save()
    Activity(race="10k", week=2, day=6, workout_type="run", distance="2.5 miles").save()
    Activity(race="10k", week=2, day=7, workout_type="run", distance="2 miles").save()

    Activity(race="10k", week=3, day=1, workout_type="rest").save()
    Activity(race="10k", week=3, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=3, day=3, workout_type="run", distance="2.5 miles").save()
    Activity(race="10k", week=3, day=4, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=3, day=5, workout_type="rest").save()
    Activity(race="10k", week=3, day=6, workout_type="run", distance="2.5 miles").save()
    Activity(race="10k", week=3, day=7, workout_type="run", distance="2 miles").save()

    Activity(race="10k", week=4, day=1, workout_type="rest").save()
    Activity(race="10k", week=4, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=4, day=3, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=4, day=4, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=4, day=5, workout_type="rest").save()
    Activity(race="10k", week=4, day=6, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=4, day=7, workout_type="run", distance="2 miles").save()

    Activity(race="10k", week=5, day=1, workout_type="rest").save()
    Activity(race="10k", week=5, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=5, day=3, workout_type="run", distance="2.5 miles").save()
    Activity(race="10k", week=5, day=4, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=5, day=5, workout_type="rest").save()
    Activity(race="10k", week=5, day=6, workout_type="run", distance="3.5 miles").save()
    Activity(race="10k", week=5, day=7, workout_type="run", distance="2.5 miles").save()

    Activity(race="10k", week=6, day=1, workout_type="rest").save()
    Activity(race="10k", week=6, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=6, day=3, workout_type="run", distance="2.5 miles").save()
    Activity(race="10k", week=6, day=4, workout_type="run", distance="2.5 miles").save()
    Activity(race="10k", week=6, day=5, workout_type="rest").save()
    Activity(race="10k", week=6, day=6, workout_type="run", distance="4 miles").save()
    Activity(race="10k", week=6, day=7, workout_type="run", distance="2.5 miles").save()

    Activity(race="10k", week=7, day=1, workout_type="rest").save()
    Activity(race="10k", week=7, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=7, day=3, workout_type="run", distance="3 miles").save()
    Activity(race="10k", week=7, day=4, workout_type="run", distance="2.5 miles").save()
    Activity(race="10k", week=7, day=5, workout_type="rest").save()
    Activity(race="10k", week=7, day=6, workout_type="run", distance="4.5 miles").save()
    Activity(race="10k", week=7, day=7, workout_type="run", distance="3 miles").save()

    Activity(race="10k", week=8, day=1, workout_type="rest").save()
    Activity(race="10k", week=8, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=8, day=3, workout_type="run", distance="2.5 miles").save()
    Activity(race="10k", week=8, day=4, workout_type="run", distance="2.5 miles").save()
    Activity(race="10k", week=8, day=5, workout_type="rest").save()
    Activity(race="10k", week=8, day=6, workout_type="run", distance="3 miles").save()
    Activity(race="10k", week=8, day=7, workout_type="run", distance="3 miles").save()

    Activity(race="10k", week=9, day=1, workout_type="rest").save()
    Activity(race="10k", week=9, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=9, day=3, workout_type="run", distance="3 miles").save()
    Activity(race="10k", week=9, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="10k", week=9, day=5, workout_type="rest").save()
    Activity(race="10k", week=9, day=6, workout_type="run", distance="5 miles").save()
    Activity(race="10k", week=9, day=7, workout_type="run", distance="3 miles").save()

    Activity(race="10k", week=10, day=1, workout_type="rest").save()
    Activity(race="10k", week=10, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=10, day=3, workout_type="run", distance="3.5 miles").save()
    Activity(race="10k", week=10, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="10k", week=10, day=5, workout_type="rest").save()
    Activity(race="10k", week=10, day=6, workout_type="run", distance="5.5 miles").save()
    Activity(race="10k", week=10, day=7, workout_type="run", distance="3 miles").save()

    Activity(race="10k", week=11, day=1, workout_type="rest").save()
    Activity(race="10k", week=11, day=2, workout_type="crosstrain").save()
    Activity(race="10k", week=11, day=3, workout_type="run", distance="3.5 miles").save()
    Activity(race="10k", week=11, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="10k", week=11, day=5, workout_type="rest").save()
    Activity(race="10k", week=11, day=6, workout_type="run", distance="4 miles").save()
    Activity(race="10k", week=11, day=7, workout_type="run", distance="3 miles").save()

    Activity(race="10k", week=12, day=1, workout_type="rest").save()
    Activity(race="10k", week=12, day=2, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=12, day=3, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=12, day=4, workout_type="run", distance="2 miles").save()
    Activity(race="10k", week=12, day=5, workout_type="rest").save()
    Activity(race="10k", week=12, day=6, workout_type="rest").save()
    Activity(race="10k", week=12, day=7, workout_type="RACE DAY", distance="6.2 miles").save()

def full_marathon():
    Activity(race="full", week=1, day=1, workout_type="rest").save()
    Activity(race="full", week=1, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=1, day=3, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=1, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=1, day=5, workout_type="rest").save()
    Activity(race="full", week=1, day=6, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=1, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=2, day=1, workout_type="rest").save()
    Activity(race="full", week=2, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=2, day=3, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=2, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=2, day=5, workout_type="rest").save()
    Activity(race="full", week=2, day=6, workout_type="run", distance="9 miles").save()
    Activity(race="full", week=2, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=3, day=1, workout_type="rest").save()
    Activity(race="full", week=3, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=3, day=3, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=3, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=3, day=5, workout_type="rest").save()
    Activity(race="full", week=3, day=6, workout_type="run", distance="10 miles").save()
    Activity(race="full", week=3, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=4, day=1, workout_type="rest").save()
    Activity(race="full", week=4, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=4, day=3, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=4, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=4, day=5, workout_type="rest").save()
    Activity(race="full", week=4, day=6, workout_type="run", distance="7 miles").save()
    Activity(race="full", week=4, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=5, day=1, workout_type="rest").save()
    Activity(race="full", week=5, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=5, day=3, workout_type="run", distance="6 miles").save()
    Activity(race="full", week=5, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=5, day=5, workout_type="rest").save()
    Activity(race="full", week=5, day=6, workout_type="run", distance="12 miles").save()
    Activity(race="full", week=5, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=6, day=1, workout_type="rest").save()
    Activity(race="full", week=6, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=6, day=3, workout_type="run", distance="6 miles").save()
    Activity(race="full", week=6, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=6, day=5, workout_type="rest").save()
    Activity(race="full", week=6, day=6, workout_type="rest").save()
    Activity(race="full", week=6, day=7, workout_type="run", distance="13.1 miles").save()

    Activity(race="full", week=7, day=1, workout_type="rest").save()
    Activity(race="full", week=7, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=7, day=3, workout_type="run", distance="7 miles").save()
    Activity(race="full", week=7, day=4, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=7, day=5, workout_type="rest").save()
    Activity(race="full", week=7, day=6, workout_type="run", distance="10 miles").save()
    Activity(race="full", week=7, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=8, day=1, workout_type="rest").save()
    Activity(race="full", week=8, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=8, day=3, workout_type="run", distance="7 miles").save()
    Activity(race="full", week=8, day=4, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=8, day=5, workout_type="rest").save()
    Activity(race="full", week=8, day=6, workout_type="run", distance="15 miles").save()
    Activity(race="full", week=8, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=9, day=1, workout_type="rest").save()
    Activity(race="full", week=9, day=2, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=9, day=3, workout_type="run", distance="8 miles").save()
    Activity(race="full", week=9, day=4, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=9, day=5, workout_type="rest").save()
    Activity(race="full", week=9, day=6, workout_type="run", distance="16 miles").save()
    Activity(race="full", week=9, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=10, day=1, workout_type="rest").save()
    Activity(race="full", week=10, day=2, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=10, day=3, workout_type="run", distance="8 miles").save()
    Activity(race="full", week=10, day=4, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=10, day=5, workout_type="rest").save()
    Activity(race="full", week=10, day=6, workout_type="run", distance="12 miles").save()
    Activity(race="full", week=10, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=11, day=1, workout_type="rest").save()
    Activity(race="full", week=11, day=2, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=11, day=3, workout_type="run", distance="9 miles").save()
    Activity(race="full", week=11, day=4, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=11, day=5, workout_type="rest").save()
    Activity(race="full", week=11, day=6, workout_type="run", distance="18 miles").save()
    Activity(race="full", week=11, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=12, day=1, workout_type="rest").save()
    Activity(race="full", week=12, day=2, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=12, day=3, workout_type="run", distance="9 miles").save()
    Activity(race="full", week=12, day=4, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=12, day=5, workout_type="rest").save()
    Activity(race="full", week=12, day=6, workout_type="run", distance="14 miles").save()
    Activity(race="full", week=12, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=13, day=1, workout_type="rest").save()
    Activity(race="full", week=13, day=2, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=13, day=3, workout_type="run", distance="10 miles").save()
    Activity(race="full", week=13, day=4, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=13, day=5, workout_type="rest").save()
    Activity(race="full", week=13, day=6, workout_type="run", distance="20 miles").save()
    Activity(race="full", week=13, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=14, day=1, workout_type="rest").save()
    Activity(race="full", week=14, day=2, workout_type="run", distance="5 miles").save()
    Activity(race="full", week=14, day=3, workout_type="run", distance="8 miles").save()
    Activity(race="full", week=14, day=4, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=14, day=5, workout_type="rest").save()
    Activity(race="full", week=14, day=6, workout_type="run", distance="12 miles").save()
    Activity(race="full", week=14, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=15, day=1, workout_type="rest").save()
    Activity(race="full", week=15, day=2, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=15, day=3, workout_type="run", distance="6 miles").save()
    Activity(race="full", week=15, day=4, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=15, day=5, workout_type="rest").save()
    Activity(race="full", week=15, day=6, workout_type="run", distance="8 miles").save()
    Activity(race="full", week=15, day=7, workout_type="crosstrain").save()

    Activity(race="full", week=16, day=1, workout_type="rest").save()
    Activity(race="full", week=16, day=2, workout_type="run", distance="3 miles").save()
    Activity(race="full", week=16, day=3, workout_type="run", distance="4 miles").save()
    Activity(race="full", week=16, day=4, workout_type="run", distance="2 miles").save()
    Activity(race="full", week=16, day=5, workout_type="rest").save()
    Activity(race="full", week=16, day=6, workout_type="rest").save()
    Activity(race="full", week=16, day=7, workout_type="RACE DAY", distance="26.2 miles").save()


def clear_data():
    """Deletes all the table data"""
    Activity.objects.all().delete()

class Command(BaseCommand):
    def handle(self, *args, **options):
        clear_data()
        # half_marathon()
        # five_k()
        # ten_k()
        # full_marathon()
        print("completed")